version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:  # Đảm bảo thụt dòng đúng, cùng cấp với nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel
    volumes:
      - .:/var/www/html
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
